algoritmo "escolha-pesquisa-marca-simples"

var

//Declaração da variável ; Especificávelmente para uma função única//

op : caractere

inicio

//Aqui é onde se inicia a operação//

Escreval("QUAIS DESSAS MARCAS SÃO AS MELHORES:")
Escreval("Opções:")
Escreval("1-NIKE")
Escreval("2-ADIDAS")
Escreval("3-PUMA")
leia(op)

//mostre o resultado armazenado pela variável especifíca//

Escreval("Você Escolheu Como Resposta:",op,("-Obrigado!"))

Fimalgoritmo