algoritmo "VETOR"

var

nomes : vetor [1..5] de caractere
contadorloop : inteiro

inicio

PARA contadorloop DE 1 ATE 5 FACA
ESCREVA("POR FAVOR , DIGITE OS NOMES : DE : " , contadorloop , " ATE 5:")
LEIA (nomes[contadorloop])
FIMPARA

PARA contadorloop DE 1 ATE 5 FACA
ESCREVAL("OS NOMES SÃO : ", nomes[contadorloop])
FIMPARA

ESCREVAL("- OBRIGADO POR REGISTRÁ-LOS!")

fimalgoritmo